import './globals.css'
import Header from '../../componentz/Header'

export const metadata = {
  title: 'Nedo',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body>
      
     <Header> </Header>

        
        {children}</body>
    </html>
  )
}
